# an example of a config that contains 

#### independent_variables
# this section contains a list of dictionaries, each containing 
#   key: [values]
# pairs. 
# any independent variables that co-vary are grouped into a single dictionary
# whose values are the same length. a zip() over the values is used in the product
# between the values.

independent_variables:
  - dataset.td_prob: [0, 1]
  - dataset.role_n_congruence: [0]
  - dataset.n_back: [5]
    dataset.concurrent_reg: [5]
  - model.model_class: ['rnn']
  - model.from_pretrained: ['model_checkpoints/blxjbcz7', 'model_checkpoints/aq7zcggi']

#### conditional variables
# this section contains conditional variables---they aren't used to define
# conditions like above (the independent variables). rather, they are
# looked-up based on matching index. 
# we go sequentially through the list of conditional variables and iterate
# over the index. for each key, value in the index we try to match the current
# instance of parameter combinations of independent variables. if all the index
# key-values match those in the independent variables, we offload the kwargs
# therein. if at least one key-value in the index does not match the independent
# variables, we keep looking.
# the ordering of the index entries matters: the first match is the one that is
# applied.  so, if you place an entry whose index has the sole key-value
# "model.model_class: 'rnn'" at the beginning of the list, that is the only set
# of kwargs that will apply *any time* the model_class is rnn, even if there is
# a more specific n_back-conditioned learning_rate value further along. so,
# place the most narrowly-scoped index entries at the top of the list and the
# most general and widely-scoped index entries at the end. i.e., defaults, if any,
# should go at the very end. 

conditional_variables:
### rnn
  - index:
      model.model_class: 'rnn'
      dataset.td_prob: 0
    kwargs:
      trainer.learning_rate: 2e-4
  - index:
      model.model_class: 'rnn'
      dataset.td_prob: 1
    kwargs:
      trainer.learning_rate: 2e-4